### ISSUE TITLE
-

### ISSUE THREAD

**Issue by ghost** [things4it/JTLShop-Plugin-CategoryImageGeneration#14]
-

**Comment by klosteinmann** [comment]
Update also scheinbar, werden Kategorien angeblich als erstellt ausgegeben obwohl dort gar kein Bild vorhanden ist.

![image](https://user-images.githubusercontent.com/34807323/179729975-64680df0-05c6-405a-a5bc-24d253b0f15a.png)

[Siehe hier.](https://iw-nord.de/?k=40116)

**Comment by klosteinmann** [comment]
Es ist momentan nicht möglich, ein Bilder-Cache bei uns im Shop zu generieren. Daher werde ich versuchen vorzuschlagen ein Shop Update auf die neuste Version auszulösen. Vielleicht behebt dies eines der Probleme.
