### ISSUE TITLE
Installieren - Plugin denkt es ist nicht aktuell

### ISSUE THREAD

**Issue by csaeum** [things4it/JTLShop-Plugin-CategoryImageGeneration#9]
![grafik](https://user-images.githubusercontent.com/1543510/127314329-f93f7f65-7267-466a-9497-545e29e6a796.png)
Ich habe dein Plugin gelöscht mit allen Inhalten und auf das vom Extensionstore umgestellt.

Leider erscheint bei mir immer wieder das "installieren" obwohl dies schon gemacht ist.

V 1.1.0

**Comment by jwendig** [comment]
Also ich kann es in meiner dev-umgebung zumindest mal reproduzieren und im prinzip "fixen".

In der Tabelle *tplugin* ist die *exsID* nicht gesetzt
![image](https://user-images.githubusercontent.com/14175881/127388409-0f6cbeec-6d87-42da-b206-d5cdc25d6a5d.png)

In \JTL\License\Mapper::setReference wird die "Erweiterung" mit der Lizenz "verheiratet" und dann via \JTL\License\Struct\ReferencedPlugin::initByExsID initialisiert. Bei der initialisierung wird das Plugin über die *exsID* gesucht und nicht gefunden - daher wird \JTL\License\Struct\ReferencedItem::setCanBeUpdated nicht auf false gesetzt ...
![image](https://user-images.githubusercontent.com/14175881/127389527-44d49dc6-6f8e-4761-a970-49033c3bfdf0.png)

Manipuliert man die DB und fügt die entsprechende *exsID* bei dem Plugin ein, passt es.

Warum die *exsID* fehlt muss ich schauen - aber das sollte das Problem sein.
Ich würde es ja gerne auf den Shop-Core schieben, aber bei anderen Plugin funktioniert es ja auch *mist* :)

**Comment by jwendig** [comment]
Sodale ... in der info.xml fehlt noch die ExsID ... danke @csaeum fürs reporten :)
